environment:
  matrix:
    - GENERATOR: "Visual Studio 14"
      CONFIG: Debug

    - GENERATOR: "Visual Studio 14 Win64"
      CONFIG: Release

build_script:
  - cmake "-G%GENERATOR%" -H. -Bbuild --debug-output --debug-trycompile
  - cmake --build build --config "%CONFIG%"

test_script:
  - ps: cd build
  - ctest -VV -C "%CONFIG%"